### ISSUE TITLE
命令好像有问题呢，还有图片输出也有问题

### ISSUE THREAD

**Issue by lhq19971216** [soulteary/docker-gitbook-pdf-generator#5]
GitHub中教我们打的命令是`pwd`/fonts:/app/fonts \
博客上却是`pwd`/fonts:/usr/share/fonts \

还有原网页是<img src="../assets/demo.jpg" alt="">
输出后却变成了<img src="http://192.168.179.101/../assets/demo.jpg alt=" "="">
导致图片无法显示，因为名称变成了demo.jpg alt=

请解决一下这两个问题呗~

**Comment by soulteary** [comment]
感谢反馈。
