### ISSUE TITLE
pull docker image是非常慢呢

### ISSUE THREAD

**Issue by cnscorpions** [soulteary/docker-gitbook-pdf-generator#8]

**Comment by lingr7** [comment]
遇到了同样的问题。真的非常慢了。
参考[解决docker pull 速度慢问题 - BillyYang - 博客园](https://www.cnblogs.com/BillyYoung/p/11113914.html)
这样可以提速，阿里云镜像非常快，可以用everything搜索daemon.json这个文件修改。

**Comment by cnscorpions** [comment]
我本地的docker有换源的，
```
{
  "registry-mirrors": [
    "https://dockerhub.azk8s.cn",
    "https://reg-mirror.qiniu.com"
  ],
  "insecure-registries": [],
  "debug": true,
  "experimental": true
}
```
不过没有加阿里源

**Comment by soulteary** [comment]
可以尝试执行工具目录本地的 `make-images.sh` ，自行构建镜像来解决问题。
